dependenciesrefactoring

diff --git a/.github/workflows/maven-testng-allure.yml b/.github/workflows/maven-testng-allure.yml
--- a/.github/workflows/maven-testng-allure.yml
+++ b/.github/workflows/maven-testng-allure.yml
@@ -7,81 +7,24 @@ on:
     branches: [ main ]
 
 #refactoring!
-defaults:
-  run:
-    shell: bash
+#defaults:
+#  run:
+#    shell: bash
 
-#    runs-on: ubuntu-latest
+#jobs:
+#  maven-save:
+#    runs-on: ${{ matrix.os }}
 #    permissions:
 #      contents: write
 #    concurrency:
 #      group: ${{ github.workflow }}-${{ github.ref }}
-
-jobs:
-  maven-save:
-    runs-on: ${{ matrix.os }}
-    permissions:
-      contents: write
-    concurrency:
-      group: ${{ github.workflow }}-${{ github.ref }}
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ubuntu-latest]
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Set up JDK 11
-        uses: actions/setup-java@v3
-        with:
-          java-version: '11'
-          distribution: 'temurin'
-          cache: maven
-
-      - name: Create files to cache
-        run: |
-          mvn verify -f __tests__/cache/maven/pom.xml
-          if [ ! -d ~/.m2/repository ]; then
-            echo "::error::The ~/.m2/repository directory does not exist unexpectedly"
-            exit 1
-          fi
-  maven-restore:
-    runs-on: ${{ matrix.os }}
-    permissions:
-      contents: write
-    concurrency:
-      group: ${{ github.workflow }}-${{ github.ref }}
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ubuntu-latest]
-    needs: maven-save
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Set up JDK 11
-        uses: actions/setup-java@v3
-        with:
-          java-version: '11'
-          distribution: 'temurin'
-          cache: maven
-
-      - name: Confirm that ~/.m2/repository directory has been made
-        run: |
-          if [ ! -d ~/.m2/repository ]; then
-            echo "::error::The ~/.m2/repository directory does not exist unexpectedly"
-            exit 1
-          fi
-          ls ~/.m2/repository
-#  build:
-#    runs-on: ubuntu-latest
-#    permissions:
-#      contents: write
-#    concurrency:
-#      group: ${{ github.workflow }}-${{ github.ref }}
-#
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        os: [ubuntu-latest]
 #    steps:
-#      - uses: actions/checkout@v3
+#      - name: Checkout
+#        uses: actions/checkout@v3
 #      - name: Set up JDK 11
 #        uses: actions/setup-java@v3
 #        with:
@@ -89,25 +32,66 @@ jobs:
 #          distribution: 'temurin'
 #          cache: maven
 #
-#      - name: Cache dependencies
-#        uses: actions/cache@v3
+#      - name: Create files to cache
+#        run: |
+#          mvn verify -f __tests__/cache/maven/pom.xml
+#          if [ ! -d ~/.m2/repository ]; then
+#            echo "::error::The ~/.m2/repository directory does not exist unexpectedly"
+#            exit 1
+#          fi
+#  maven-restore:
+#    runs-on: ${{ matrix.os }}
+#    permissions:
+#      contents: write
+#    concurrency:
+#      group: ${{ github.workflow }}-${{ github.ref }}
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        os: [ubuntu-latest]
+#    needs: maven-save
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v3
+#      - name: Set up JDK 11
+#        uses: actions/setup-java@v3
 #        with:
-#          path: ~/.m2/repository
-#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
-#          restore-keys: |
-#            ${{ runner.os }}-maven-
-#      - run: mvn install -DskipTests
+#          java-version: '11'
+#          distribution: 'temurin'
+#          cache: maven
+#
+#      - name: Confirm that ~/.m2/repository directory has been made
+#        run: |
+#          if [ ! -d ~/.m2/repository ]; then
+#            echo "::error::The ~/.m2/repository directory does not exist unexpectedly"
+#            exit 1
+#          fi
+#          ls ~/.m2/repository
+jobs:
+  build:
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+    concurrency:
+      group: ${{ github.workflow }}-${{ github.ref }}
 
+    steps:
+      - uses: actions/checkout@v3
+      - name: Set up JDK 11
+        uses: actions/setup-java@v3
+        with:
+          java-version: '11'
+          distribution: 'temurin'
+          cache: maven
 
       - name: Cache dependencies
         uses: actions/cache@v3
         with:
-          path: ~/.m2/repository
-          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+          path: ~/.m2
+          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
           restore-keys: |
-            ${{ runner.os }}-maven-
-      - run: mvn install -DskipTests
-
+            ${{ runner.os }}-m2-
+      - run: mvn verify -DskipTests
 
       - name: Build with Maven
         if: always()
@@ -140,14 +124,3 @@ jobs:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_branch: gh-pages
           publish_dir: allure-history
-
-#      - name: Post the link to the report
-#        if: always()
-#        uses: Sibz/github-status-action@v1
-#        with:
-#          authToken: ${{secrets.GITHUB_TOKEN}}
-#          context: 'Test report'
-#          description: 'Passed'
-#          state: 'success'
-#          sha: ${{ github.event.pull_request.head.sha }}
-#          target_url: simple-elf.github.io/github-allure-history/${{ github.run_number }}
