cash mavn

diff --git a/.github/workflows/maven-testng-allure.yml b/.github/workflows/maven-testng-allure.yml
--- a/.github/workflows/maven-testng-allure.yml
+++ b/.github/workflows/maven-testng-allure.yml
@@ -1,28 +1,89 @@
 name: Java CI with Maven
 
-#on: [ push ]
-
 on:
-#  schedule:
-#    - cron: '00 18 * * *'
+  #  schedule:
+  #    - cron: '00 18 * * *'
   push:
     branches: [ main ]
-    pull_request:
-      branches: [ main ]
+
+#refactoring!
+defaults:
+  run:
+    shell: bash
 
 jobs:
-  build:
-
-    runs-on: ubuntu-latest
-
+  maven-save:
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [macos-latest, windows-latest, ubuntu-latest]
     steps:
-      - uses: actions/checkout@v3
-      - name: Set up JDK 11
-        uses: actions/setup-java@v3
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Run setup-java with the cache for maven
+        uses: ./
+        id: setup-java
         with:
+          distribution: 'adopt'
           java-version: '11'
-          distribution: 'temurin'
           cache: maven
+      - name: Create files to cache
+        run: |
+          mvn verify -f __tests__/cache/maven/pom.xml
+          if [ ! -d ~/.m2/repository ]; then
+            echo "::error::The ~/.m2/repository directory does not exist unexpectedly"
+            exit 1
+          fi
+  maven-restore:
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [macos-latest, windows-latest, ubuntu-latest]
+    needs: maven-save
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Run setup-java with the cache for maven
+        uses: ./
+        id: setup-java
+        with:
+          distribution: 'adopt'
+          java-version: '11'
+          cache: maven
+      - name: Confirm that ~/.m2/repository directory has been made
+        run: |
+          if [ ! -d ~/.m2/repository ]; then
+            echo "::error::The ~/.m2/repository directory does not exist unexpectedly"
+            exit 1
+          fi
+          ls ~/.m2/repository
+#  build:
+#    runs-on: ubuntu-latest
+#    permissions:
+#      contents: write
+#    concurrency:
+#      group: ${{ github.workflow }}-${{ github.ref }}
+#
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: Set up JDK 11
+#        uses: actions/setup-java@v3
+#        with:
+#          java-version: '11'
+#          distribution: 'temurin'
+#          cache: maven
+#
+#      - name: Cache dependencies
+#        uses: actions/cache@v3
+#        with:
+#          path: ~/.m2/repository
+#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+#          restore-keys: |
+#            ${{ runner.os }}-maven-
+#      - run: mvn install -DskipTests
+
       - name: Build with Maven
         if: always()
         run: mvn clean test -Dsurefire.suiteXmlFiles=./src/test/resources/suites/frontend/e2e.xml -Dspring.profiles.active=stage
@@ -45,16 +106,12 @@ jobs:
           gh_pages: gh-pages
           allure_report: allure-report
           allure_history: allure-history
+          keep_reports: 20
 
       - name: Deploy report to Github Pages
         if: always()
         uses: peaceiris/actions-gh-pages@v3
-#        env:
         with:
-# PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-#          deploy_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
-#          github_token: ${{ secrets.GITHUB_TOKEN }}
-#          repo-token: ${{ secrets.GITHUB_TOKEN }}
-          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
+          github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_branch: gh-pages
           publish_dir: allure-history
